#!/usr/bin/env bash
# Scaffold config for a new enterprise client (custom-distribution app).
#
# Usage: scripts/new-client.sh <client-slug>
#   <client-slug>  short lowercase id, e.g. "laa" → shopify.app.laa.toml,
#                  cloud_run_env_laa.yaml, Cloud Run service ello-vto-laa
#
# Generates the two config files with REPLACE_ME placeholders and prints the
# fill-in checklist. Compliance flags (SKIP_BILLING / BILLING_TEST_MODE /
# APP_DISTRIBUTION) are carried over verbatim — a custom-distribution app must
# never real-bill through Shopify. See FABLE-ENTERPRISE-AUDIT-REPORT.md §5.
set -euo pipefail
cd "$(dirname "$0")/.."

SLUG="${1:?usage: scripts/new-client.sh <client-slug>}"
case "$SLUG" in
  *[!a-z0-9-]*) echo "ERROR: slug must be lowercase letters/digits/hyphens" >&2; exit 1;;
esac

TOML="shopify.app.${SLUG}.toml"
ENVF="cloud_run_env_${SLUG}.yaml"
[ -e "$TOML" ] && { echo "ERROR: $TOML already exists" >&2; exit 1; }
[ -e "$ENVF" ] && { echo "ERROR: $ENVF already exists" >&2; exit 1; }

SERVICE_URL="https://REPLACE_ME_SERVICE_URL"

cat > "$TOML" <<EOF
# Per-client custom-distribution app config — generated by scripts/new-client.sh
# Client: ${SLUG}
# Fill every REPLACE_ME, then: npm run lint && npm run typecheck && npm run build
# Deploy order: Cloud Run first (to learn the service URL), then update this
# file + the env yaml with the real URL, redeploy, then scripts/deploy-client.sh.

client_id = "REPLACE_ME_CLIENT_ID"
name = "Ello VTO — REPLACE_ME_CLIENT_NAME"
application_url = "${SERVICE_URL}"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Catalog changes must bump config_version so the widget's cached
  # enabled-handles list (ETag) invalidates — otherwise new products never
  # show the try-on button in 'all'/'collections' mode until settings re-save.
  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/delete", "products/update" ]
  uri = "/webhooks/products"

  # Refunds feed Qualified Revenue "net of returns" (term-sheet item). Requires
  # the read_orders scope below + Partner Dashboard protected-customer-data
  # approval; without both, Shopify never delivers refunds and rev-share
  # over-states revenue. Mirror of shopify.app.custom.toml.
  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds"

[access_scopes]
scopes = "read_products,read_orders,unauthenticated_read_product_listings,unauthenticated_read_product_tags,read_customer_events,read_pixels,write_pixels,read_themes"

[auth]
redirect_urls = [ "${SERVICE_URL}/auth/callback" ]
EOF

# Env file: start from the custom app's env, blank the app-specific secrets,
# and make sure SUPABASE_ANON_KEY is present (missing from the legacy custom
# yaml — the widget-config fallback path returns "" without it).
cp cloud_run_env_custom.yaml "$ENVF"
sed -i '' -E 's#^(SHOPIFY_API_KEY:).*#\1 "REPLACE_ME_CLIENT_ID"#' "$ENVF"
sed -i '' -E 's#^(SHOPIFY_API_SECRET:).*#\1 "REPLACE_ME_CLIENT_SECRET"#' "$ENVF"
sed -i '' -E "s#^(SHOPIFY_APP_URL:).*#\1 \"${SERVICE_URL}\"#" "$ENVF"
if ! grep -q '^SUPABASE_ANON_KEY:' "$ENVF"; then
  if anon_line=$(grep '^SUPABASE_ANON_KEY:' cloud_run_env.yaml); then
    printf '%s\n' "$anon_line" >> "$ENVF"
  else
    echo 'SUPABASE_ANON_KEY: "REPLACE_ME_SUPABASE_ANON_KEY"' >> "$ENVF"
  fi
fi

# Guard: the three compliance flags must have survived the copy.
for flag in SKIP_BILLING BILLING_TEST_MODE APP_DISTRIBUTION; do
  grep -q "^${flag}:" "$ENVF" || { echo "ERROR: $flag missing from $ENVF — copy from cloud_run_env_custom.yaml" >&2; exit 1; }
done

cat <<EOF

Created: $TOML, $ENVF

FILL IN (from the Partner Dashboard after creating the custom-distribution app):
  1. REPLACE_ME_CLIENT_ID / REPLACE_ME_CLIENT_SECRET  (both files)
  2. REPLACE_ME_CLIENT_NAME                            ($TOML)
  3. REPLACE_ME_SERVICE_URL — first deploy Cloud Run to learn it:
       npm run lint && npm run typecheck && npm run build
       gcloud run deploy ello-vto-${SLUG} --source . --region us-central1 \\
         --env-vars-file $ENVF --allow-unauthenticated --memory 2Gi \\
         --update-secrets=TELEGRAM_BOT_TOKEN=telegram-bot-token:latest
     then put the printed URL into both files and redeploy.
  4. ML_API_URL in $ENVF — decide which render engine this client uses.

THEN:
  5. Clone the CDN worker (cloudflare/wrangler-client.toml.template) →
     widget-${SLUG}.ellotryon.com
  6. scripts/deploy-client.sh ${SLUG} https://widget-${SLUG}.ellotryon.com
  7. scripts/verify-client.sh https://widget-${SLUG}.ellotryon.com <run.app URL> <store-slug>

Full playbook: vault Outreach/Client-Signing-Day0-Runbook.md
EOF
